# Default values for kratos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: oryd/kratos
  tag: v0.5.5-alpha.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  admin:
    enabled: true
    type: ClusterIP
    port: 80
    # If you do want to specify annotations, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'annotations:'.
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  public:
    enabled: true
    type: ClusterIP
    port: 80
    # If you do want to specify annotations, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'annotations:'.
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

secret:
  # switch to false to prevent creating the secret
  enabled: true
  # ... and choose a different name for a secret you provide like this
  # nameOverride: "MyOtherName"

ingress:
  admin:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: kratos.admin.local.com
        paths:
          - /

    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  public:
    enabled: false
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      -
        host: kratos.public.local.com
        paths:
          - /

    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

# Postgres Database
postgresql:
  # service.port: 5432
  postgresqlDatabase: kratos
  postgresqlUsername: kratos
  postgresqlPassword: secret

kratos:  
  development: false
  autoMigrate: true

#  You can add multiple identity schemas here
  identitySchemas:
    "identity.schema.json": |
      {
        "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Person",
        "type": "object",
        "properties": {
          "traits": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email",
                "title": "E-Mail",
                "minLength": 3,
                "ory.sh/kratos": {
                  "credentials": {
                    "password": {
                      "identifier": true
                    }
                  },
                  "verification": {
                    "via": "email"
                  },
                  "recovery": {
                    "via": "email"
                  }
                }
              },
              "name": {
                "type": "object",
                "properties": {
                  "first": {
                    "type": "string"
                  },
                  "last": {
                    "type": "string"
                  }
                }
              }
            },
            "required": [
              "email"
            ],
            "additionalProperties": false
          }
        }
      }
    # "identity.email.schema.json": |
    #  {
    #    // ...
    #  }

  config:
    # TODO - Need to move dsn to template so that we can eliminate hard-coded values like
    # host, user, password and secret here.
    dsn: postgres://kratos:secret@kratos-postgresql:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4

    serve:
      public:
        port: 4433
        base_url: http://127.0.0.1:4433/
        cors:
          enabled: true
      admin:
        port: 4434
        base_url: http://kratos-admin.ory.svc.cluster.local/

    selfservice:
      default_browser_return_url: http://127.0.0.1:4455/
      whitelisted_return_urls:
        - http://127.0.0.1:4455
        - http://127.0.0.1:3000

      methods:
        password:
          enabled: true

      flows:
        error:
          ui_url: http://127.0.0.1:4455/error

        settings:
          ui_url: http://127.0.0.1:4455/settings
          privileged_session_max_age: 15m

        recovery:
          enabled: true
          ui_url: http://127.0.0.1:4455/recovery

        verification:
          enabled: true
          ui_url: http://127.0.0.1:4455/verify
          after:
            default_browser_return_url: http://127.0.0.1:4455/

        logout:
          after:
            default_browser_return_url: http://127.0.0.1:4455/auth/login

        login:
          ui_url: http://127.0.0.1:4455/auth/login
          lifespan: 8h
          after:
            default_browser_return_url: http://127.0.0.1:3000

        registration:
          lifespan: 8h
          ui_url: http://127.0.0.1:4455/auth/registration
          after:
            default_browser_return_url: http://127.0.0.1:3000
            password:
              hooks:
                -
                  hook: session

    log:
      level: debug
      format: text
      leak_sensitive_values: true

    secrets: {}

    hashers:
      argon2:
        parallelism: 1
        memory: 131072
        iterations: 2
        salt_length: 16
        key_length: 16

    identity:
      default_schema_url: file:///etc/config/identity.schema.json

    courier:
      smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true


deployment:
  resources: {}
  #  We usually recommend not to specify default resources and to leave this as a conscious
  #  choice for the user. This also increases chances charts run on environments with little
  #  resources, such as Minikube. If you do want to specify resources, uncomment the following
  #  lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 100m
  #  memory: 128Mi

  # Node labels for pod assignment.
  nodeSelector: {}
  # If you do want to specify node labels, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'annotations:'.
  #   foo: bar

  # Configure node tolerations.
  tolerations: []

  labels: {}
  #      If you do want to specify additional labels, uncomment the following
  #      lines, adjust them as necessary, and remove the curly braces after 'labels:'.
  #      e.g.  type: app

  annotations: {}
  #      If you do want to specify annotations, uncomment the following
  #      lines, adjust them as necessary, and remove the curly braces after 'annotations:'.
  #      e.g.  sidecar.istio.io/rewriteAppHTTPProbers: "true"

  # The secret specified here will be used to load environment variables with envFrom.
  # This allows arbitrary environment variables to be provided to the application which is useful for
  # sensitive values which should not be in a configMap.
  # This secret is not created by the helm chart and must already exist in the namespace.
  # https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#configure-all-key-value-pairs-in-a-secret-as-container-environment-variables
  environmentSecretsName:

# Configure node affinity
affinity: {}
