apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailslurper.fullname" . }}
  labels:
    {{- include "mailslurper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http }}
      targetPort: {{ .Values.service.http }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.api }}
      targetPort: {{ .Values.service.api }}
      protocol: TCP
      name: api
    - port: {{ .Values.service.smtp }}
      targetPort: {{ .Values.service.smtp }}
      protocol: TCP
      name: smtp            
  selector:
    {{- include "mailslurper.selectorLabels" . | nindent 4 }}
